AWSTemplateFormatVersion: '2010-09-09'
Description: Architettura ad alta disponibilità per WordPress con RDS replica in standby

Parameters:
  AMIVersion:
    Description: Version of AMI
    Type: AWS::EC2::Image::Id

  WordPressVersion:
    Description: Version of WordPress to install
    Type: String
    Default: latest
    AllowedValues: [latest, 6.2.2, 6.2.1, 6.2, 6.1.3, 6.1.2, 6.1.1, 6.1, 5.8.1, 5.8, 5.7.3, 5.7, 5.6.4, 5.6, 5.5.6, 5.5, 5.4.7, 5.4]

  VpcCidrBlock:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CidrBlock:
    Description: CIDR block for the public subnet 1
    Type: String
    Default: 10.0.0.0/24

  PublicSubnet2CidrBlock:
    Description: CIDR block for the public subnet 2
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet1CidrBlock:
    Description: CIDR block for the private subnet 1
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet2CidrBlock:
    Description: CIDR block for the private subnet 2
    Type: String
    Default: 10.0.3.0/24

  StorageEncrypted:
    Description: StorageEncrypted parameter
    Type: String
    Default: "false"
    AllowedValues: 
      - true 
      - false

  MultiAZ:
    Description: MultiAZ parameter
    Type: String
    Default: "false"
    AllowedValues: 
      - true 
      - false

  AdminDBName:
    Description: Admin's DB name
    Type: String

  AdminDBPassword:
    Description: Admin's DB password
    Type: String

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/vpc.yaml
      Parameters:
        VpcCidrBlock: !Ref VpcCidrBlock

  SubnetsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/subnets.yaml
      Parameters:
        PublicSubnet1CidrBlock: !Ref PublicSubnet1CidrBlock
        PublicSubnet2CidrBlock: !Ref PublicSubnet2CidrBlock
        PrivateSubnet1CidrBlock: !Ref PrivateSubnet1CidrBlock
        PrivateSubnet2CidrBlock: !Ref PrivateSubnet2CidrBlock

 # NATGatewayEIPStack:
  #  Type: AWS::CloudFormation::Stack
   # Properties:
    #  TemplateURL: https://s3.console.aws.amazon.com/s3/object/rootandnested?region=us-west-1&prefix=exercisecube/internetgateway.yaml
     # Parameters:
      #  VPCId: !GetAtt VPCStack.Outputs.VpcId

  InternetGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/internetgateway.yaml

  RoutingTablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/routingtables.yaml

  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/targetgroup.yaml

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/loadbalancer.yaml

  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/autoscaling.yaml
      Parameters:
        WordPressVersion: !Ref WordPressVersion
        AMIVersion: !Ref AMIVersion

#  RDSStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: rds.yaml
#      Parameters:
#        AdminDBName: !Ref AdminDBName
#        AdminDBPassword: !Ref AdminDBPassword
#        MultiAZ: !Ref MultiAZ
#        StorageEncrypted: !Ref StorageEncrypted

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://rootandnested.s3.us-west-1.amazonaws.com/exercisecube/securitygroups.yaml
  
#  CloudFrontStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: cloudfront.yaml

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the load balancer
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNSName
