# rds.yaml

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref SubnetGroupStack.Outputs.DBSubnetGroupName
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: '5.7'
      MasterUsername: !Ref AdminDBName
      MasterUserPassword: !Ref AdminDBPassword
      MultiAZ: !Ref MultiAZ
      StorageType: gp2
      StorageEncrypted: !Ref StorageEncrypted

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "subnetgroup"
      DBSubnetGroupDescription: "Subnet Group per l'istanza database"
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
